//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BlueUI.rc
//
#define IDCANCLE                        2
#define IDD_ABOUTBOX                    100
#define IDD_TPS_PLATFORM                101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_DIALOGFLASH                 112
#define CG_IDD_PROGRESS                 116
#define IDR_MAINFRAME                   128
#define IDR_BLUEUITYPE                  129
#define IDB_OPTIONTREE                  130
#define IDB_BITMAP_ABOUT_TITLE          131
#define IDR_POPUP_TABS                  132
#define IDI_PROPERTY                    134
#define IDI_DISPLAY                     135
#define IDD_TREE_OPTIONS                136
#define IDD_TPS_ASSOCIATE               137
#define IDB_REPORT_CTRL                 138
#define IDR_EXPLORER                    140
#define IDR_POPUP_WORKSPACE             141
#define IDR_OUTPUT                      142
#define IDI_VCI                         143
#define IDD_TPS_FONT                    144
#define IDD_TPS_LANGUAGE                145
#define IDD_TPS_UISTYLE                 146
#define IDI_ICON_INFO                   154
#define IDI_ICON_WARN                   156
#define IDI_ICON_ERROR                  157
#define IDI_CLOSE                       159
#define IDB_OPTIONS                     173
#define IDR_OUTPUT_GRID                 184
#define IDI_ICON_FONT                   192
#define IDB_TITLE                       209
#define IDB_OPTION_TITLE                220
#define IDI_ICON_DIRECT                 225
#define IDB_CLOSEMSN                    300
#define FIRST_STATUS_COMMAND            500
#define LAST_STATUS_COMMAND             549
#define FIRST_TOOL_COMMAND              550
#define LAST_TOOL_COMMAND               650
#define FIRST_IMPORT_COMMAND            680
#define LAST_IMPORT_COMMAND             689
#define FIRST_EXPORT_COMMAND            690
#define LAST_EXPORT_COMMAND             699
#define IDC_ASSOCIATE_TREE              1000
#define IDC_COMBO_LANGUAGE              1001
#define IDC_LOGIN_PASSWORD              1002
#define IDC_COMBO_HTML_STYLE            1003
#define IDC_REPORT                      1004
#define CG_IDC_PROGDLG_PROGRESS         1005
#define IDC_LIST_ITEM                   1006
#define CG_IDC_PROGDLG_STATUS           1007
#define IDC_COMBO_FONT                  1008
#define IDC_COMBO_SIZE                  1009
#define IDC_COLORFG_PICKER              1010
#define IDC_COLORBK_PICKER              1011
#define IDC_CHECK_BOLD                  1013
#define IDC_CHECK_ITALIC                1015
#define IDC_CHECK_STRIKEOUT             1016
#define IDC_CHECK_UNDERLINE             1017
#define IDC_SAMPLEBOX                   1018
#define IDC_STATIC_FONT                 1057
#define IDC_STATIC_SIZE                 1058
#define IDC_STATIC_COLORFG              1059
#define IDC_STATIC_COLORBK              1060
#define IDC_LOGIN_USERNAME              1064
#define IDC_BTN_FONTRESET               1065
#define IDC_LOGIN_ADDRESS               1066
#define IDC_COMBO_DOMAIN                1067
#define IDC_STATIC_MSG                  1086
#define IDC_STATIC_FLASH                1087
#define IDC_CHECK_DIRECT_OUTPUT         1088
#define IDC_CHECK_DIRECT_FILE           1089
#define IDC_LIST_THEMES                 1090
#define IDC_CHECK_DIRECT_RESULT         1090
#define IDC_CHECK_APPLYFRAME            1091
#define IDC_CHECK_DIRECT_PIPE           1092
#define IDC_CHECK_APPLYMETRICS          1093
#define IDC_CHECK_DIRECT_MEMORY         1094
#define IDC_CHECK_APPLYCOLORS           1095
#define IDC_CHECK_DIRECT_ADMIN          1096
#define IDC_COMBO_COLORS                1097
#define IDC_EDIT_DIRECT_OUTPUTID        1098
#define IDC_COMBO_FONTS                 1099
#define IDC_SPIN_TCL_DIRECT_OUTPUTID    1100
#define IDC_RADIO_OFFICE2000            1103
#define IDC_RADIO_OFFICEXP              1104
#define IDC_RADIO_OFFICE2003            1106
#define IDC_RADIO_WINTHEME              1107
#define IDC_RADIO_WHIDBEY               1108
#define IDC_RADIO_OFFICE2007            1109
#define IDC_RADIO_RIBBON                1110
#define IDC_RADIO_OFFICE2003_BLUE       1112
#define IDC_RADIO_OFFICE2003_OLIVE      1114
#define IDC_RADIO_OFFICE2003_METALLIC   1116
#define IDC_CHECK_RELOAD_DOCUMENT       1118
#define IDC_CHECK_AUTO_OPEN_STARTPAGE   1119
#define IDC_CHECK_ENABLE_DEBUGOUT       1120
#define IDC_CHECK_ADD_SHELL_CONTEXT_MENU 1120
#define IDC_CHECK_LOGIN                 1121
#define IDC_STATIC_INFO                 1122
#define IDC_STATIC_PICTURE              1126
#define IDD_TPS_INTERP_DIRECT           3014
#define IDD_TCL_LOGIN                   3019
#define IDD_TPS_WORKSPACE               3020
#define IDD_TPS_VCI                     3021
#define IDR_PANE_OPTIONS                4000
#define IDR_PANE_PROPERTIES             4001
#define IDB_OPTIONMARKS                 4002
#define IDC_TITLE                       10057
#define ID_OEDIT_COPY                   25782
#define ID_OEDIT_CUT                    25783
#define ID_OFILE_SAVE                   25784
#define ID_OEDIT_CLEAR                  25785
#define ID_OEDIT_SELECTALL              25890
#define IDC_LABEL_ADDRESS               25903
#define IDC_LABEL_USERNAME              25904
#define IDC_LABEL_PASSWORD              25905
#define IDC_LABEL_DOMAIN                25906
#define ID_OUTCTRL_CLOSE                25919
#define ID_OUTCTRL_DELROW               25920
#define ID_OUTCTRL_SCRIPT               25923
#define ID_OEDIT_SEARCH                 25934
#define ID_OEDIT_SEARCH_AGAIN           25935
#define ID_OUTCTRL_SELFDEFINE           25936
#define ID_EXPORT_EXCEL                 25953
#define ID_PANEPROPERIES_CATEGORIZED    26000
#define ID_PANEPROPERIES_ALPHABETIC     26001
#define ID_VIEW_PROPERTIES              26002
#define ID_VIEW_OUTPUT                  26003
#define IDS_MENUBAR                     26004
#define IDS_STANDARD                    26005
#define ID_OPTION                       26010
#define ID_VCI_MANAGER                  26011
#define IDS_TITLE_TREEPROPSHEET_SYSCFG  26013
#define IDS_FONT_TREEPROPSHEET          26014
#define IDS_TREEPROPSHEET_DATAVERIFYFAIL 26015
#define IDS_TREEPROPSHEET_CTRL_OK       26016
#define IDS_TREEPROPSHEET_CTRL_CANCEL   26017
#define IDS_TREEPROPSHEET_CTRL_APPLY    26018
#define IDS_TREEPROPSHEET_CTRL_HELP     26019
#define IDS_TPS_FONT_OUTPUT             26020
#define IDS_TPS_FONT                    26021
#define IDS_TPS_ABOUT_FONT              26022
#define ID_OPEN_WITH                    26023
#define IDS_TPS_LANGUAGE                26024
#define IDS_TPS_ABOUT_LANGUAGE          26025
#define IDS_TPS_ASSOCIATE               26026
#define ID_PROJECT_NEWFILE              26027
#define IDS_TPS_ABOUT_ASSOCIATE         26029
#define IDS_TPS_OWM                     26030
#define IDS_TPS_ABOUT_OWM               26032
#define IDS_TPS_INTERP                  26033
#define IDS_TPS_ABOUT_INTERP            26034
#define IDS_TPS_VCI                     26035
#define ID_VIEW_LOG                     26036
#define IDS_TPS_ABOUT_VCI               26037
#define IDS_TPS_UISTYLE                 26038
#define IDS_TPS_ABOUT_UISTYLE           26039
#define ID_HELP_TOPICS                  26042
#define ID_HELP_REGISTERATE             26043
#define ID_HELP_UPGRADE                 26044
#define ID_HELP_HOMEPAGE                26045
#define ID_HELP_BUGREPORT               26046
#define IDS_TPS_PLATFORM                26047
#define ID_GOTO_URL                     26048
#define IDS_TPS_ABOUT_PLATFORM          26049
#define IDS_TPS_ASS_DOCNAME             26050
#define IDS_TPS_ASS_DOCEXT              26051
#define IDS_TPS_ASS_OWMID               26052
#define IDS_TPS_ASS_ASSOCIATE           26053
#define ID_FILE_NEW_BLANK               26054
#define ID_REFRESH_GOTO_URL             26055
#define ID_WINDOW_CLOSE_ALL             26057
#define ID_TOGGLE_DOCK                  26058
#define IDS_STOP_INTERP_FIRST           26059
#define ID_TOOLS_EXTEND                 26060
#define IDS_TPS_WORKSPACE               26061
#define IDS_TPS_ABOUT_WORKSPACE         26062
#define IDS_TPS_INTERP_DIRECT           26063
#define ID_EXTEND_TOOLS                 26064
#define IDS_TITLE_TREEPROPSHEET_PROJECTCFG 26065
#define IDS_TPS_ABOUT_INTERP_DIRECT     26066
#define IDS_INFO_OUTPUT_SCRIPT          26068
#define ID_HELP_DOWNLOAD                26069
#define IDS_INFO_OUTPUT_SCRIPT_TITLE    26070
#define ID_PROJECT_NEW                  26074
#define ID_PROJECT_OPEN                 26075
#define ID_PROJECT_SAVE                 26076
#define ID_PROJECT_CLOSE                26077
#define ID_PROJECT_BUILD                26078
#define ID_PROJECT_REBUILD              26079
#define ID_PROJECT_CLEAN                26080
#define ID_PROJECT_INFO                 26081
#define ID_PROJECT_PROPERTY             26082
#define ID_PROJECT_RUN                  26083
#define IDS_PROJECT_WORKING             26084
#define IDS_INFO_OPEN_PROJECT           26085
#define IDS_INFO_NEW_PROJECT            26086
#define IDS_INFO_SAVE_PROJECT           26087
#define IDS_INFO_RUN_PROJECT            26088
#define IDS_INFO_CLOSE_PROJECT          26089
#define IDS_INFO_BUILD_PROJECT          26090
#define IDS_INFO_REBUILD_PROJECT        26091
#define IDS_INFO_CLEAN_PROJECT          26092
#define IDS_LOAD_LICENSE_FAILED         26093
#define ID_FILE_LOADSESSION             26095
#define ID_FILE_SAVESESSION             26096
#define ID_FILE_PRINT_PAGESETUP         26098
#define IDS_TITLE_TREEPROPSHEET_PRINTPAGESETUP 26099
#define ID_EXPORT_FILES                 26100
#define IDR_PANE_OUTPUT                 30000
#define IDM_OWMCMD                      40000
#define IDS_LOGIN_TITLE                 50699
#define IDS_LOGIN_INFO                  50700
#define IDS_TITLE_TREEOPTDLG            50701
#define IDS_INFO_TREEOPTDLG_MUSTINPUT   50702

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         26104
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
