//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PTerminal.rc
//
#define IDD_DIALOG_COMPARAM             109
#define IDR_TELNET                      128
#define IDB_EDIT_AUTOCOMPLETE           171
#define IDB_TITLE                       209
#define IDC_COMBO_STOPBITS              1003
#define IDC_COMBO_PARITY                1004
#define IDC_COMBO_DATABITS              1005
#define IDC_COMBO_COM                   1007
#define IDC_COMBO_BAUD                  1008
#define IDC_CHECK_ECHO                  3000
#define IDD_ABOUTBOX                    3001
#define IDC_EDIT_LIST                   3001
#define IDC_CHECK_ENABLE_LISTDLG        3001
#define IDR_OWM                         3002
#define IDR_CONTEXT                     3002
#define IDR_TERM_TCL                    3003
#define IDI_TELNET                      3004
#define IDC_COMBO_DEFAULTSHELL          3004
#define IDR_ACCELERATOR1                3005
#define IDC_EDIT_TCLINTERPNAME          3005
#define IDR_ACCELERATOR                 3005
#define IDC_EDIT_PYTHONINTERPNAME       3006
#define IDB_LOGO_ATESTUDIOOWM           3006
#define IDI_COM                         3007
#define IDR_OWM_VIEW                    3008
#define ID_INDICATOR_INFO               6701
#define ID_INDICATOR_TERMTYPE           6702
#define ID_INDICATOR_SHELL              6703
#define IDD_TPS_PTERMINAL               8603
#define ID_TELNET_CONNECT               11351
#define ID_TELNET_DISCONNECT            11352
#define ID_OWM_ABOUT                    11353
#define ID_VIEW_OWM                     11354
#define IDS_DEFAULTTEXTFONT             11355
#define IDS_DEFAULTFONT                 11356
#define ID_TERM_OPENFILE                11357
#define ID_LIST_COMMAND                 11358
#define ID_LIST_HISTORYCMD              11359
#define ID_LIST_LOADLIB                 11360
#define ID_LIST_KNOWNLIB                11361
#define ID_LIST_GLOBALS                 11362
#define ID_LIST_LOCALVARS               11363
#define ID_LIST_PROCS                   11364
#define ID_LIST_ITCLOBJECT              11366
#define ID_SERVER_CONNECT               11368
#define ID_SERVER_DISCONNECT            11369
#define ID_SWITCH_TERMINAL              11370
#define ID_PROP_COMMAND_LIST            11371
#define ID_RESET_INTERP                 11372
#define ID_VIEW_TERMINAL                40110
#define IDS_TERM_LOCAL                  57643
#define IDS_CONN_LOCAL                  57644
#define IDS_TERM_TYPE_STD               57645
#define IDS_TERM_TCL                    57646
#define IDS_TCL_INTERP                  57647
#define IDS_TERM_TELNET                 57648
#define IDS_TERM_TYPE_VT                57649
#define IDS_TERM_COM                    57650
#define IDS_TERM_REMOTE                 57651
#define IDS_SOCK_CLOSE                  57652
#define IDS_SOCK_RC_OUTBAND_DATA        57653
#define IDS_OWM_CONSOLE                 57654
#define IDS_MENU_CONSOLE                57655
#define IDS_STR_CONSOLE                 57656
#define IDS_PROP_ABOUT                  57657
#define IDS_STR_LOGIN                   57660
#define IDS_LOGIN_TELNET_FAIL           57661
#define IDS_TCL_FILE_FILTER             57662
#define IDS_TCLCMD_USE_TOTAL            57663
#define IDS_TCLCMD_KERNEL_LIB           57664
#define IDS_TCLCMD_KERNEL_LIB_TOTAL     57665
#define IDS_TCLCMD_EXPAND               57666
#define IDS_TCLCMD_LIST                 57667
#define IDS_TCLCMD_USE_INFO             57668
#define IDS_TCLCMD_HISTORY_TOTAL        57669
#define IDS_TCLCMD_HISTORY_LIST         57670
#define IDS_TCLCMD_HISTORY_INFO         57671
#define IDS_TCLDLL_TOTAL                57672
#define IDS_TCLDLL_LIST                 57673
#define IDS_TCLDLL_INFO                 57674
#define IDS_TCLPROC_TOTAL               57675
#define IDS_TCLPROC_LIST                57676
#define IDS_TCLPROC_INFO                57677
#define IDS_GLOBEVAR_TOTAL              57678
#define IDS_GLOBEVAR_LIST               57679
#define IDS_GLOBEVAR_INFO               57680
#define IDS_LOCAL_TOTAL                 57681
#define IDS_LOCAL_IN_PROC               57682
#define IDS_LOCAL_OUT_PROC              57683
#define IDS_LOCAL_LIST                  57684
#define IDS_ITCL_TOTAL                  57685
#define IDS_ITCL_LIST                   57686
#define IDS_ITCL_INFO                   57687
#define IDS_DOMAIN_TELNET               57688
#define IDS_TERM_PYTHON                 57689
#define IDS_PYTHON_INTERP               57690
#define IDS_DOMAIN_RCADMIN              57691
#define IDS_INTERPRETER_NAME            57691
#define IDS_LOGIN_RCADMIN_FAIL          57692
#define IDS_RC_INTERPRETER              57693
#define IDS_TCL_RCINTERP                57694
#define IDS_PYTHON_FILE_FILTER          57695
#define IDS_SWITCH_SHELL                57696
#define IDS_TELNET_LOGIN_INFO           57697
#define IDS_TELNET_PORT_LABEL           57698
#define IDS_TOOL_MENU                   57699
#define IDS_TELNET_ENABLE_ANSI_COLOR    57700
#define IDS_TELNET_ADDRESS_LABEL        57701
#define IDS_TELNET_DOMAIN_LABEL         57702
#define IDS_TERM_RUBY                   57703
#define IDS_TERM_LUA                    57704
#define IDS_TERM_PERL                   57705
#define IDS_RUBY_INTERP                 57706
#define IDS_LUA_INTERP                  57707
#define IDS_PERL_INTERP                 57708
#define IDS_RUBY_FILE_FILTER            57709
#define IDS_LUA_FILE_FILTER             57710
#define IDS_PERL_FILE_FILTER            57711

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3009
#define _APS_NEXT_COMMAND_VALUE         11373
#define _APS_NEXT_CONTROL_VALUE         3002
#define _APS_NEXT_SYMED_VALUE           3002
#endif
#endif
